-- MySQL Script generated by MySQL Workbench
-- Fri Feb  7 22:08:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Chelyshkoff Cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Chelyshkoff Cinema
-- -----------------------------------------------------
CREATE DATABASE ChelyshkoffCinema;
USE ChelyshkoffCinema;

-- -----------------------------------------------------
-- Table `Chelyshkoff Cinema`.`Admines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChelyshkoffCinema`.`Admines` (
  `idAdmines` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Password` VARCHAR(100) NULL,
  `Surname` VARCHAR(45) NULL,
  `Email` VARCHAR(60) NULL,
  PRIMARY KEY (`idAdmines`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chelyshkoff Cinema`.`Cinemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChelyshkoffCinema`.`Cinemas` (
  `idCinema` INT NOT NULL,
  `Tile` VARCHAR(45) NOT NULL DEFAULT 'Chelyshkoff Cinema',
  `Город` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(45) NULL,
  `HouseNumber` VARCHAR(45) NULL,
  `HallsNumber` VARCHAR(45) NULL,
  `idAdmin` INT NULL,
  PRIMARY KEY (`idCinema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chelyshkoff Cinema`.`Rows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChelyshkoffCinema`.`Rows` (
  `idRows` INT NOT NULL,
  `SeatsNumber` INT NULL,
  PRIMARY KEY (`idRows`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chelyshkoff Cinema`.`Halls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChelyshkoffCinema`.`Halls` (
  `idHall` INT NOT NULL,
  `idCinema` INT NULL,
  `idRow` INT NOT NULL,
  `RowsNumber` INT NULL,
  PRIMARY KEY (`idHall`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chelyshkoff Cinema`.`Films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChelyshkoffCinema`.`Films` (
  `idFilms` INT NOT NULL auto_increment,
  `Title` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `Genre` VARCHAR(45) NULL,
  `Limitation` VARCHAR(4) NULL,
  `Description` LONGTEXT NULL,
  `TrailerLink` VARCHAR(100) NULL,
  `PosterLink` VARCHAR(100) NULL,
  PRIMARY KEY (`idFilms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chelyshkoff Cinema`.`Sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChelyshkoffCinema`.`Sessions` (
  `idSessions` INT NOT NULL auto_increment,
  `idHall` INT NULL,
  `Date` DATETIME NULL,
  `Start` VARCHAR(45) NULL,
  `End` VARCHAR(45) NULL,
  `Cost` DOUBLE NULL,
  `VideoFormat` VARCHAR(45) NULL,
  `AudioFormat` VARCHAR(45) NULL,
  `idFilm` INT NULL,
  PRIMARY KEY (`idSessions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chelyshkoff Cinema`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChelyshkoffCinema`.`Users` (
  `idUsers` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chelyshkoff Cinema`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChelyshkoffCinema`.`Tickets` (
  `idTickets` INT NOT NULL,
  `FilmTitle` VARCHAR(45) NULL,
  `idSession` INT NULL,
  `Start` VARCHAR(45) NULL,
  `End` VARCHAR(45) NULL,
  `Row` INT NULL,
  `SeatsNumber` INT NULL,
  `Hall` INT NULL,
  PRIMARY KEY (`idTickets`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chelyshkoff Cinema`.`UserTicket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChelyshkoffCinema`.`UserTicket` (
  `idUser` INT NOT NULL,
  `idTicket` INT NULL)
ENGINE = InnoDB;
