-- MySQL Script generated by MySQL Workbench
-- Fri Mar 20 00:16:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema Chelyshkoff Cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cinema` DEFAULT CHARACTER SET utf8 ;
USE `Cinema` ;

-- -----------------------------------------------------
-- Table `Cinema`.`Cinemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Cinemas` (
  `idCinema` INT NOT NULL AUTO_INCREMENT,
  `Tile` VARCHAR(45) NOT NULL DEFAULT 'Cinema',
  `Город` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(100) NULL,
  `HallsNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`idCinema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Halls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Halls` (
  `idHall` INT NOT NULL AUTO_INCREMENT,
  `HallsNumber` INT NOT NULL,
  `SeatsInRow` INT NOT NULL,
  `RowsNumber` INT NULL,
  PRIMARY KEY (`idHall`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Films` (
  `idFilms` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `Genre` VARCHAR(45) NULL,
  `Limitation` VARCHAR(4) NULL,
  `Description` LONGTEXT NULL,
  `TrailerLink` VARCHAR(100) NULL,
  `PosterLink` VARCHAR(100) NULL,
  PRIMARY KEY (`idFilms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Sessions` (
  `idSessions` INT NOT NULL AUTO_INCREMENT,
  `idHall` INT NULL,
  `Date` DATETIME NULL,
  `Start` TIME NULL,
  `End` TIME NULL,
  `Cost` DOUBLE NULL,
  `VideoFormat` VARCHAR(45) NULL,
  `AudioFormat` VARCHAR(45) NULL,
  `idFilm` INT NULL,
  PRIMARY KEY (`idSessions`),
  CONSTRAINT `idHall`
    FOREIGN KEY (`idHall`)
    REFERENCES `Cinema`.`Halls` (`idHall`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idFilm`
    FOREIGN KEY (`idFilm`)
    REFERENCES `Cinema`.`Films` (`idFilms`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Admines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Admines` (
  `idAdmines` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Password` VARCHAR(100) NULL,
  `Surname` VARCHAR(45) NULL,
  `Email` VARCHAR(60) NULL,
  PRIMARY KEY (`idAdmines`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Tickets` (
  `idTickets` INT NOT NULL AUTO_INCREMENT,
  `FilmTitle` VARCHAR(45) NULL,
  `idSession` INT NULL,
  `Row` INT NULL,
  `SeatsNumber` INT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idTickets`),
  CONSTRAINT `idSession`
    FOREIGN KEY (`idSession`)
    REFERENCES `Cinema`.`Sessions` (`idSessions`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `Cinema`.`Users` (`idUsers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Cinema`.`CinemasHalls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`CinemasHalls` (
  `idCinema` INT NOT NULL,
  `idHall` INT NOT NULL,
  CONSTRAINT `Hall`
    FOREIGN KEY (`idHall`)
    REFERENCES `Cinema`.`Halls` (`idHall`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Cinema`
    FOREIGN KEY (`idCinema`)
    REFERENCES `Cinema`.`Cinemas` (`idCinema`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chelyshkoff Cinema`.`Seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Seats` (
  `idSeats` INT NOT NULL AUTO_INCREMENT,
  `idHall` INT NOT NULL,
  `row` INT NOT NULL,
  `column` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'free',
  PRIMARY KEY (`idSeats`),
  CONSTRAINT `SeatstoHall`
    FOREIGN KEY (`idHall`)
    REFERENCES `Cinema`.`Halls` (`idHall`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

